### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AntoineTesson**
Since Symfony 3.x , console is on the bin folder

### CODE REVIEW

**Comment by CoalaJoe** [comment]
Symfony 2.7 is still supported. I'd suggest to add both and label them.

**Comment by ProPheT777** [comment]
thanks @AntoineTesson, can you add both as ask @CoalaJoe please ? Since we support both version. 

Thank you for your contribution!

**Comment by AntoineTesson** [comment]
Hi, ok i have set the two possibility with older version and newtest

**Comment by AntoineTesson** [comment]
https://github.com/GeniusesOfSymfony/WebSocketBundle/pull/217/commits/b752d9c89daa4e6c38b37a48cf9c7e3ce94aa331

**Comment by ProPheT777** [comment]
Perfect, thank you @AntoineTesson :+1:

**Pull request merged**
