### PR TITLE
pdo session handler

### PR DESCRIPTION
**Pull request by AntoineTesson**
Hi, 
with SYMFONY 3.3 the old configuration throw an exception.
I have set the new way to process.

### CODE REVIEW

**Comment by CoalaJoe** [comment]
Can you please remove the IDE specific files and folders, they don't belong here.

**Comment by AntoineTesson** [comment]
I'm sory. how delete files who are useless ? 
And i wait , because this new way cause exceptions ... 
look : https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/240

**Comment by CoalaJoe** [comment]
Use this tool. https://help.github.com/articles/removing-sensitive-data-from-a-repository/
For the future, you can create a global .gitignore, which will then work on all repositories without including them.

**Comment by ProPheT777** [comment]
Could you remove all noisy files not related to the project please ?

**Pull request closed without merging**
